<?php

/**
 * @file
 * Primary module hooks for AweKnow module module.
 */

 /**
 * Implements hook_theme().
 */
function weknow_module_theme($existing, $type, $theme, $path) {
  return [
    'weknow' => [
      'variables' => [
        'form_link1' => NULL,
        'form_link2' => NULL
      ],
    ],
  ];
}

/**
 * Implements hook_contact_entity_count_incremented().
 */
function weknow_module_contact_entity_count_incremented($count, $entity) {
  $messenger = \Drupal::messenger();
  $messenger->addStatus(t('Dos This is the first time you have viewed the contact entity %count.', array('%count' => $count, '%title' => $entity->label())));
}
/**
 * Implements hook_contact_entity_count_incremented_alter().
 */
function weknow_module_contact_entity_count_incremented_alter(&$current_counts) {
    $current_counts[] = $current_counts[1] - 5;
}
