<?php

/**
 * @file
 * Primary module hooks for AweKnow module module.
 */

use Drupal\Core\Url;

 /**
 * Implements hook_theme().
 */
function weknow_module_theme($existing, $type, $theme, $path) {
  return [
    'weknow' => [
      'variables' => [
        'form_link1' => NULL,
        'form_link2' => NULL
      ],
    ],
  ];
}

/**
 * Implements hook_contact_entity_count_incremented().
 */
function weknow_module_contact_entity_count_incremented($count, $entity) {
  $messenger = \Drupal::messenger();
  $messenger->addStatus(t('Dos This is the first time you have viewed the contact entity %count.', array('%count' => $count, '%title' => $entity->label())));
}
/**
 * Implements hook_contact_entity_count_incremented_alter().
 */
function weknow_module_contact_entity_count_incremented_alter(&$current_counts) {
    $current_counts[] = $current_counts[1] - 5;
}

function weknow_module_menu_links_discovered_alter(&$links) {
  // Change the weight and title of the user.logout link.
  $links["user.page"]["title"] = new \Drupal\Core\StringTranslation\TranslatableMarkup('User account');
  // Conditionally add an additional link with a title that's not translated.
   if (\Drupal::moduleHandler()->moduleExists('weknow_module')) {
     $links['example_page_translate'] = array(
      'title' => \Drupal::config('system.site')->get('name'),
      'route_name' => 'weknow_module.translate',
      'menu_name' => 'main',
      'description' => new \Drupal\Core\StringTranslation\TranslatableMarkup('View examples translates page.'),
    );
  }
}

function weknow_module_menu_local_actions_alter(&$local_actions) {
  if (array_key_exists('weknow_module.add_vendor', $local_actions)) {
    $local_actions["weknow_module.add_vendor"]["title"] = 'Other title add vendor';
  }

}

function weknow_module_contextual_links_alter(array &$links, $group, array $route_parameters) {
  if ($group == 'menu') {
    // Dynamically use the menu name for the title of the menu_edit contextual
    // link.
    $menu = \Drupal::entityTypeManager()->getStorage('menu')->load($route_parameters['menu']);
    $links['entity.menu.edit_form']['title'] = t('Edit menu: @label', array('@label' => $menu->label()));
  }
}

function weknow_module_contextual_links_view_alter(&$element, $items) {
  // Add another class to all contextual link lists to facilitate custom
  // styling.
  $element['#attributes']['class'][] = 'custom-class';
}

function  weknow_module_menu_local_tasks_alter(&$data, $route_name) {

  // Add a tab linking to node/add to all pages.
  $data['tabs'][0]['node.add_page'] = array(
    '#theme' => 'menu_local_task',
    '#link' => array(
      'title' => t('Add content'),
      'url' => Url::fromRoute('node.add_page'),
      'localized_options' => array(
        'attributes' => array(
          'class' => array('example-tab'),
        ),
      ),
    ),
  );
}
