display:
  default:
    display_options:
      title: Recetas
      exposed_form:
        options:
          submit_button: Aplicar
      filters:
        field_ingredients_target_id:
          expose:
            label: 'Encontrar recetas usando...'
