_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  automated_cron: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_list_override: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  colorbox: 0
  comment: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_translation: 0
  consumers: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  diff: 0
  do_projects: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_usage: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  jsonapi: 0
  jsonapi_defaults: 0
  jsonapi_extras: 0
  language: 0
  layout_builder: 0
  layout_builder_modal: 0
  layout_builder_restrictions: 0
  layout_builder_styles: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_entity_twitter: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  oembed_providers: 0
  openapi: 0
  openapi_jsonapi: 0
  openapi_ui: 0
  openapi_ui_redoc: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  react_block: 0
  responsive_image: 0
  rest: 0
  restui: 0
  schemata: 0
  schemata_json_schema: 0
  search: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_pantheon: 0
  search_api_solr: 0
  search_api_solr_autocomplete: 0
  search_api_solr_legacy: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  weknow_module: 0
  workflows: 0
  pathauto: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  bartik: 0
  seven: 0
  weknowtheme: 0
profile: standard
