_core:
  default_config_hash: rzLRjfCTsgd4s021DeXFUboiQb_74hMz6pmmst50Neo
enabled: true
extension: xhprof
exclude: "/contextual/*\r\n/toolbar/*\r\n/edit/*\r\n/admin/*\r\n/profiler/*\r\n*.js\r\n*.css"
interval: 0
flags:
  FLAGS_CPU: '0'
  FLAGS_MEMORY: '0'
  FLAGS_NO_BUILTINS: '0'
exclude_indirect_functions: false
storage: xhprof.file_storage
show_summary_toolbar: null
